### ISSUE TITLE
Import Error: No module named metaswitch.ellis.data

### ISSUE THREAD

**Issue by gremaudc** [Metaswitch/ellis#105]
Hello, 

I'm trying to run create_numbers.py but I have the following error:

`[cw-aio]ubuntu@cw-aio:/usr/share/clearwater/ellis/src/metaswitch/ellis/data$ sudo python create_numbers.py --start 41264751000 --count 25
Traceback (most recent call last):
  File "create_numbers.py", line 44, in <module>
    from metaswitch.ellis.data import numbers, connection
ImportError: No module named metaswitch.ellis.data
`

**Comment by mirw** [comment]
Hi!

You need to use the Python environment in `/usr/share/clearwater/ellis/env/bin`, either by running `/usr/share/clearwater/ellis/env/bin/python` rather than `python` or by adding this directory to your path, e.g. with `export PATH=/usr/share/clearwater/ellis/env/bin:$PATH`.

Also, I notice that you're running from `/usr/share/clearwater/ellis/src/metaswitch/ellis/data` - there is no `create_numbers.py` there - you need to be in `/usr/share/clearwater/ellis/src/metaswitch/ellis/tools`.

Please can you try these changes?

Also, please can you let me know if there were particular documents you were referring to here - we should probably get them fixed up?

Thanks,

Matt

**Comment by eleanor-merry** [comment]
I've looked through the documentation now
