### ISSUE TITLE
Homestead-prov's list_users script does not list users in any sensible ordering

### ISSUE THREAD

**Issue by AME2** [Metaswitch/ellis#200]
I've been doing some testing of Homestead-prov's subscriber provisioning/managing scripts.

I created some subscribers:

`/usr/share/clearwater/bin/create_user +5551110100..+5551110110 ame2.clearwater.test secret`

I then listed all the users provisioned against my deployment:

```
clearwater@ame2-homestead-1:~$ /usr/share/clearwater/bin/list_users
sip:+5551110103@ame2.clearwater.test
sip:+5551110106@ame2.clearwater.test
sip:+5551110100@ame2.clearwater.test
sip:+5551110101@ame2.clearwater.test
sip:+5551110110@ame2.clearwater.test
sip:+5551110107@ame2.clearwater.test
sip:+5551110105@ame2.clearwater.test
sip:+5551110104@ame2.clearwater.test
sip:+5551110108@ame2.clearwater.test
sip:+5551110102@ame2.clearwater.test
sip:+5551110109@ame2.clearwater.test
```

These are not in any order which may be unhelpful if you're looking for a particular subscriber. These should be displayed in ascending order.

**Comment by mirw** [comment]
Unfortunately, I don't think it's feasible to do any better.  We have to retrieve records from Cassandra in chunks.  We could sort all the records in one chunk into order, but we can't sort records between chunks because that would mean retrieving all chunks and storing them in memory before displaying them.  On a large scale system, we could have (say) 10M subscribers, and this wouldn't fit.

OK to close?

**Comment by AME2** [comment]
Yes in that case I'll close this issue.
